"""
State Machine Orchestration & Sacred Verification Gate.
Governing Rules:
- RULES.md §1 (The Verification Gate Is Sacred, Rules 1.1–1.5, S-17, S-18)
- IMPLEMENTATION_PLAN.md § Phase 10 (Orchestration & API)
- GUARDIAN_LOANS_ONLY_SPEC.md §3.7

State Machine:
ingest → extract → consistency-check → recompute/serviceability → generate claim → retrieve → verify → (vernacular, if requested) → respond
"""

import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import uuid4

from fastapi import HTTPException, status
from supabase import Client, create_client

from app.core.config import settings
from app.core.logging import logger
from app.schemas.claim import Claim
from app.schemas.consistency import ConsistencyCheckResponse
from app.schemas.pipeline import (
    LoanAnalysisPipelineResponse,
    PipelineStage,
    RunPipelineRequest,
    StageTiming,
)
from app.schemas.serviceability import RecomputeResponse, ServiceabilityResponse
from app.schemas.verification import VerificationResult, VerifiedClaimResponse
from app.schemas.vernacular import VernacularVerificationResponse
from modules.m0_intake.extraction import (
    extract_structured_fields_via_llm,
    fallback_regex_extraction,
)
from modules.m1_recompute.apr_recompute import recompute_apr
from modules.m1b_serviceability.serviceability import assess_serviceability
from modules.m2_consistency.consistency import run_consistency_check
from modules.m3_verifier.verifier import verify_claim
from modules.m4_vernacular.vernacular_verifier import verify_vernacular_claim
from rag.chroma_client import query_rbi_corpus, query_user_documents


def get_default_db() -> Client:
    return create_client(settings.SUPABASE_URL, settings.SUPABASE_SERVICE_ROLE_KEY)


def verify_and_resolve_claim(
    claim_id: str,
    user_id: str,
    loan_id: str,
    supabase_client: Optional[Client] = None,
) -> VerifiedClaimResponse:
    """
    THE SINGLE CHOKE-POINT FUNCTION (RULES.md §1.1).
    Every claim must pass through this function before being returned to a user.

    Ensures:
    1. Claim exists in claims table and belongs to (user_id, loan_id).
    2. A corresponding verification_results row exists or is immediately generated by Module 3.
    3. If verification status is 'flagged', is_safe_to_present is strictly False and a prominent
       warning is attached. Unverified or flagged claims are NEVER presented as fact.
    """
    supabase = supabase_client or get_default_db()

    # Step 1: Fetch Claim from Supabase
    claim_res = (
        supabase.table("claims")
        .select("*")
        .eq("claim_id", claim_id)
        .eq("user_id", user_id)
        .eq("loan_id", loan_id)
        .execute()
    )
    if not claim_res.data:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Claim {claim_id} not found for this loan and user.",
        )

    claim_data = claim_res.data[0]
    claim = Claim(**claim_data)

    # Step 2: Check if verification result already exists
    verif_res = (
        supabase.table("verification_results")
        .select("*")
        .eq("claim_id", claim_id)
        .execute()
    )

    if verif_res.data:
        v_record = verif_res.data[0]
        verification_result = VerificationResult(**v_record)
    else:
        # Step 3: Run Module 3 Dual Groundedness Verifier
        logger.info(
            f"Sacred Gate: Claim {claim_id} unverified. Triggering Module 3 verifier..."
        )
        verification_result = verify_claim(
            claim=claim,
            user_id=user_id,
            loan_id=loan_id,
            supabase_client=supabase,
        )

    # Step 4: Construct strictly-gated user response
    is_grounded = verification_result.final_verdict == "grounded"

    warning_msg = None
    if not is_grounded:
        err = verification_result.error_type or "unverified_evidence"
        warning_msg = (
            f"CAUTION: This financial claim failed dual groundedness verification ({err}). "
            "It contains potential inconsistencies or regulatory contradictions and cannot be trusted as fact."
        )

    return VerifiedClaimResponse(
        claim_id=claim.claim_id,
        source_module=claim.source_module,
        loan_id=claim.loan_id,
        claim_text=claim.claim_text,
        verification_status=verification_result.final_verdict,
        is_safe_to_present=is_grounded,
        warning_message=warning_msg,
        verification_result=verification_result,
    )


def run_full_loan_pipeline(
    loan_id: str,
    user_id: str,
    request: Optional[RunPipelineRequest] = None,
    supabase_client: Optional[Client] = None,
) -> LoanAnalysisPipelineResponse:
    """
    State machine executing the complete GUARDIAN pipeline end-to-end:
    ingest → extract → consistency-check → recompute/serviceability →
    generate claim → retrieve → verify → (vernacular, if requested) → respond

    Guarantees:
    - Microsecond stage latency tracking.
    - Every emitted claim passes strictly through verify_and_resolve_claim() (RULES.md §1.1).
    - Returns structured status, results, warnings, and verified claims.
    """
    supabase = supabase_client or get_default_db()
    req = request or RunPipelineRequest()
    timings: List[StageTiming] = []
    pipeline_start = time.perf_counter()

    current_stage = PipelineStage.INGESTING
    warnings: List[str] = []

    try:
        # -------------------------------------------------------------
        # Stage 1: INGESTING
        # -------------------------------------------------------------
        t0 = time.perf_counter()
        current_stage = PipelineStage.INGESTING

        loan_res = (
            supabase.table("loans")
            .select("*")
            .eq("id", loan_id)
            .eq("user_id", user_id)
            .execute()
        )
        if not loan_res.data:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Loan {loan_id} not found or access denied.",
            )

        terms_res = (
            supabase.table("loan_manual_terms")
            .select("*")
            .eq("loan_id", loan_id)
            .execute()
        )
        manual_terms = terms_res.data[0] if terms_res.data else None

        docs_res = (
            supabase.table("loan_documents")
            .select("*")
            .eq("loan_id", loan_id)
            .execute()
        )
        documents = docs_res.data or []

        timings.append(
            StageTiming(
                stage=PipelineStage.INGESTING,
                duration_ms=round((time.perf_counter() - t0) * 1000, 2),
            )
        )

        # -------------------------------------------------------------
        # Stage 2: EXTRACTING
        # -------------------------------------------------------------
        t0 = time.perf_counter()
        current_stage = PipelineStage.EXTRACTING

        extracted_records_by_type: Dict[str, Any] = {}
        for doc in documents:
            doc_id = doc.get("doc_id") or doc.get("id")
            doc_type = doc.get("doc_type") or doc.get("document_type")

            fields_res = (
                supabase.table("extracted_fields")
                .select("field_name, extracted_value")
                .eq("doc_id", doc_id)
                .execute()
            )
            if fields_res.data:
                rec: Dict[str, Any] = {}
                for item in fields_res.data:
                    fname = item["field_name"]
                    val = item["extracted_value"]
                    rec[fname] = (
                        val.get("value")
                        if isinstance(val, dict) and "value" in val
                        else val
                    )
                extracted_records_by_type[doc_type] = rec
            elif doc.get("raw_text"):
                # Extract fields if raw_text present but unextracted
                try:
                    terms_obj = extract_structured_fields_via_llm(
                        doc["raw_text"], doc_type=doc_type
                    )
                except Exception:
                    terms_obj = fallback_regex_extraction(doc["raw_text"])

                rec_dict = {
                    "principal": terms_obj.principal,
                    "disclosed_rate": terms_obj.disclosed_rate,
                    "tenure_months": terms_obj.tenure_months,
                    "processing_fee": terms_obj.processing_fee,
                    "prepayment_clause": terms_obj.prepayment_clause,
                }
                for f_name, f_val in rec_dict.items():
                    supabase.table("extracted_fields").insert(
                        {
                            "id": str(uuid4()),
                            "doc_id": doc_id,
                            "field_name": f_name,
                            "extracted_value": {"value": f_val},
                            "confidence": 1.0,
                            "extraction_method": "llm",
                            "created_at": datetime.now(timezone.utc).isoformat(),
                        }
                    ).execute()
                extracted_records_by_type[doc_type] = rec_dict

        timings.append(
            StageTiming(
                stage=PipelineStage.EXTRACTING,
                duration_ms=round((time.perf_counter() - t0) * 1000, 2),
            )
        )

        # -------------------------------------------------------------
        # Stage 3: CONSISTENCY_CHECKING
        # -------------------------------------------------------------
        t0 = time.perf_counter()
        current_stage = PipelineStage.CONSISTENCY_CHECKING

        consistency_response: Optional[ConsistencyCheckResponse] = None
        kfs_fields = extracted_records_by_type.get("kfs")
        tc_fields = extracted_records_by_type.get("terms_conditions")

        if kfs_fields or tc_fields or manual_terms:
            checks, overall_status, summary_explanation, requires_human_review = (
                run_consistency_check(
                    manual_terms=manual_terms,
                    tnc_extracted=tc_fields,
                    kfs_extracted=kfs_fields,
                )
            )

            m_count = sum(1 for c in checks if c.match_status == "match")
            mm_count = sum(1 for c in checks if c.match_status == "mismatch")
            miss_count = sum(1 for c in checks if c.match_status == "missing")

            consistency_response = ConsistencyCheckResponse(
                loan_id=loan_id,
                overall_status=overall_status,
                mismatch_count=mm_count,
                missing_count=miss_count,
                match_count=m_count,
                checks=checks,
                claim_id=None,
                summary_explanation=summary_explanation,
            )
            if overall_status == "mismatch":
                warnings.append(
                    f"Consistency check detected {mm_count} discrepancy(ies) across loan sources."
                )

        timings.append(
            StageTiming(
                stage=PipelineStage.CONSISTENCY_CHECKING,
                duration_ms=round((time.perf_counter() - t0) * 1000, 2),
            )
        )

        # -------------------------------------------------------------
        # Stage 4: RECOMPUTING_SERVICEABILITY
        # -------------------------------------------------------------
        t0 = time.perf_counter()
        current_stage = PipelineStage.RECOMPUTING_SERVICEABILITY

        apr_response: Optional[RecomputeResponse] = None
        serviceability_response: Optional[ServiceabilityResponse] = None

        # Determine figures from manual terms or KFS
        source_terms = manual_terms or kfs_fields
        principal = (
            float(source_terms["principal"])
            if source_terms and source_terms.get("principal")
            else None
        )
        rate = (
            float(source_terms["disclosed_rate"])
            if source_terms and source_terms.get("disclosed_rate")
            else None
        )
        tenure = (
            int(source_terms["tenure_months"])
            if source_terms and source_terms.get("tenure_months")
            else None
        )
        fee = (
            float(source_terms.get("fees") or source_terms.get("processing_fee") or 0.0)
            if source_terms
            else 0.0
        )

        if principal and rate and tenure:
            # Recompute APR
            apr_calc = recompute_apr(
                principal=principal,
                disclosed_rate=rate,
                tenure_months=tenure,
                fees=fee,
            )
            is_understated = (apr_calc.recomputed_apr - rate) > 0.05
            apr_response = RecomputeResponse(
                principal=principal,
                disclosed_rate=rate,
                tenure_months=tenure,
                fees=fee,
                disbursed_amount=round(principal - fee, 2),
                monthly_emi=apr_calc.monthly_emi,
                total_payment=apr_calc.total_payment,
                total_interest=apr_calc.total_interest,
                recomputed_apr=apr_calc.recomputed_apr,
                fee_impact_apr=round(apr_calc.recomputed_apr - rate, 2),
                claim_id=None,
            )
            if is_understated:
                warnings.append(
                    f"Understated APR: True APR is {apr_calc.recomputed_apr}% vs disclosed {rate}%."
                )

            # Serviceability check
            monthly_income = req.monthly_income
            obligations = req.existing_obligations or 0.0

            if not monthly_income:
                inc_res = (
                    supabase.table("income_expense_inputs")
                    .select("*")
                    .eq("loan_id", loan_id)
                    .execute()
                )
                if inc_res.data:
                    monthly_income = float(inc_res.data[0]["monthly_income"])
                    obligations = float(inc_res.data[0].get("existing_debts") or 0.0)

            if monthly_income and monthly_income > 0:
                s_calc = assess_serviceability(
                    monthly_income=monthly_income,
                    existing_emis=obligations,
                    monthly_expenses=0.0,
                    new_emi=apr_calc.monthly_emi,
                )
                tot_debt = round(apr_calc.monthly_emi + obligations, 2)
                disp_inc = round(monthly_income - tot_debt, 2)
                serviceability_response = ServiceabilityResponse(
                    loan_id=loan_id,
                    monthly_income=monthly_income,
                    existing_emis=obligations,
                    monthly_expenses=0.0,
                    new_emi=apr_calc.monthly_emi,
                    total_emis=tot_debt,
                    dti_ratio=s_calc.dti_ratio,
                    disposable_income=disp_inc,
                    verdict=s_calc.verdict,
                    is_heuristic=True,
                    claim_id=str(uuid4()),
                    claim_verification_status="pending",
                    claim_text_unverified=(
                        f"DTI ratio is {s_calc.dti_ratio:.2%}. Assessment verdict: {s_calc.verdict}."
                    ),
                    computed_at=datetime.now(timezone.utc),
                )
                if s_calc.verdict == "not-serviceable":
                    warnings.append(
                        f"High DTI warning: {s_calc.dti_ratio:.2%} indicates loan is not serviceable under industry heuristics."
                    )

        timings.append(
            StageTiming(
                stage=PipelineStage.RECOMPUTING_SERVICEABILITY,
                duration_ms=round((time.perf_counter() - t0) * 1000, 2),
            )
        )

        # -------------------------------------------------------------
        # Stage 5: GENERATING_CLAIM
        # -------------------------------------------------------------
        t0 = time.perf_counter()
        current_stage = PipelineStage.GENERATING_CLAIM

        created_claim_ids: List[str] = []

        # Claim A: APR Recompute Claim
        if apr_response:
            c_apr_id = str(uuid4())
            claim_text = (
                f"The borrower was disclosed an interest rate of {apr_response.disclosed_rate}%. "
                f"Accounting for the INR {apr_response.fees} processing fee, the true APR "
                f"is recomputed at {apr_response.recomputed_apr}% with a monthly EMI of INR {apr_response.monthly_emi}."
            )
            supabase.table("claims").insert(
                {
                    "claim_id": c_apr_id,
                    "user_id": user_id,
                    "loan_id": loan_id,
                    "source_module": "recompute",
                    "claim_text": claim_text,
                    "supporting_figures": {
                        "principal": apr_response.principal,
                        "disclosed_rate": apr_response.disclosed_rate,
                        "recomputed_apr": apr_response.recomputed_apr,
                        "monthly_emi": apr_response.monthly_emi,
                    },
                    "source_record_id": loan_id,
                    "generated_at": datetime.now(timezone.utc).isoformat(),
                    "verification_status": "pending",
                }
            ).execute()
            created_claim_ids.append(c_apr_id)

        # Claim B: Prepayment / Consistency Claim
        if consistency_response and consistency_response.checks:
            mismatches = [
                c for c in consistency_response.checks if c.match_status == "mismatch"
            ]
            for mm in mismatches:
                c_mm_id = str(uuid4())
                mm_text = (
                    f"Discrepancy detected in {mm.field_name}: KFS states '{mm.kfs_value}' "
                    f"whereas Terms & Conditions state '{mm.tnc_value}'."
                )
                supabase.table("claims").insert(
                    {
                        "claim_id": c_mm_id,
                        "user_id": user_id,
                        "loan_id": loan_id,
                        "source_module": "consistency",
                        "claim_text": mm_text,
                        "supporting_figures": {
                            "field_name": mm.field_name,
                            "kfs_value": mm.kfs_value,
                            "tc_value": mm.tnc_value,
                        },
                        "source_record_id": loan_id,
                        "generated_at": datetime.now(timezone.utc).isoformat(),
                        "verification_status": "pending",
                    }
                ).execute()
                created_claim_ids.append(c_mm_id)

        # Claim C: Serviceability Claim
        if serviceability_response:
            c_srv_id = str(uuid4())
            srv_text = (
                f"Borrower monthly income is INR {serviceability_response.monthly_income} with total "
                f"obligations of INR {serviceability_response.total_emis}. "
                f"Resulting Debt-to-Income (DTI) ratio is {serviceability_response.dti_ratio}% "
                f"(Industry benchmark verdict: {serviceability_response.verdict})."
            )
            supabase.table("claims").insert(
                {
                    "claim_id": c_srv_id,
                    "user_id": user_id,
                    "loan_id": loan_id,
                    "source_module": "serviceability",
                    "claim_text": srv_text,
                    "supporting_figures": {
                        "monthly_income": serviceability_response.monthly_income,
                        "dti_ratio": serviceability_response.dti_ratio,
                        "monthly_emi": serviceability_response.new_emi,
                    },
                    "source_record_id": loan_id,
                    "generated_at": datetime.now(timezone.utc).isoformat(),
                    "verification_status": "pending",
                }
            ).execute()
            created_claim_ids.append(c_srv_id)

        timings.append(
            StageTiming(
                stage=PipelineStage.GENERATING_CLAIM,
                duration_ms=round((time.perf_counter() - t0) * 1000, 2),
            )
        )

        # -------------------------------------------------------------
        # Stage 6: RETRIEVING_REGULATORY
        # -------------------------------------------------------------
        t0 = time.perf_counter()
        current_stage = PipelineStage.RETRIEVING_REGULATORY

        # Retrieve relevant passages from ChromaDB for regulatory context
        query_rbi_corpus(
            query_texts=[
                "APR disclosure and prepayment penalty guidelines for digital lending loans"
            ],
            n_results=2,
        )
        query_user_documents(
            user_id=user_id,
            loan_id=loan_id,
            query_texts=["Key Fact Statement interest rate and prepayment terms"],
            n_results=2,
        )

        timings.append(
            StageTiming(
                stage=PipelineStage.RETRIEVING_REGULATORY,
                duration_ms=round((time.perf_counter() - t0) * 1000, 2),
            )
        )

        # -------------------------------------------------------------
        # Stage 7: VERIFYING (The Sacred Gate — RULES.md §1.1)
        # -------------------------------------------------------------
        t0 = time.perf_counter()
        current_stage = PipelineStage.VERIFYING

        verified_claims: List[VerifiedClaimResponse] = []
        for c_id in created_claim_ids:
            verified_resp = verify_and_resolve_claim(
                claim_id=c_id,
                user_id=user_id,
                loan_id=loan_id,
                supabase_client=supabase,
            )
            verified_claims.append(verified_resp)

        timings.append(
            StageTiming(
                stage=PipelineStage.VERIFYING,
                duration_ms=round((time.perf_counter() - t0) * 1000, 2),
            )
        )

        # -------------------------------------------------------------
        # Stage 8: TRANSLATING_VERNACULAR (Optional)
        # -------------------------------------------------------------
        t0 = time.perf_counter()
        vernacular_results: Optional[List[VernacularVerificationResponse]] = None

        if req.target_language in ["hi", "mr"]:
            current_stage = PipelineStage.TRANSLATING_VERNACULAR
            vernacular_results = []
            for v_claim in verified_claims:
                claim_obj = Claim(
                    claim_id=v_claim.claim_id,
                    user_id=user_id,
                    loan_id=loan_id,
                    source_module=v_claim.source_module,  # type: ignore
                    claim_text=v_claim.claim_text,
                    source_record_id=loan_id,
                    verification_status=v_claim.verification_status,
                )
                v_audit = verify_vernacular_claim(
                    claim=claim_obj,
                    user_id=user_id,
                    loan_id=loan_id,
                    target_language=req.target_language,  # type: ignore
                )
                vernacular_results.append(v_audit)

        timings.append(
            StageTiming(
                stage=PipelineStage.TRANSLATING_VERNACULAR,
                duration_ms=round((time.perf_counter() - t0) * 1000, 2),
            )
        )

        # -------------------------------------------------------------
        # Stage 9: COMPLETED / RESPOND
        # -------------------------------------------------------------
        total_duration = round((time.perf_counter() - pipeline_start) * 1000, 2)
        is_compliant = len(warnings) == 0 and all(
            vc.verification_status == "grounded" for vc in verified_claims
        )

        summary_parts = [
            f"Loan analysis completed in {total_duration}ms across {len(timings)} stages."
        ]
        if is_compliant:
            summary_parts.append(
                "All loan terms match KFS and meet regulatory standards."
            )
        else:
            summary_parts.append(f"{len(warnings)} compliance concern(s) flagged.")

        # Log pipeline execution to audit_log (S-21)
        supabase.table("audit_log").insert(
            {
                "user_id": user_id,
                "action": "PIPELINE_ANALYSIS_COMPLETED",
                "entity_type": "loan",
                "entity_id": loan_id,
                "metadata": {
                    "total_duration_ms": total_duration,
                    "verified_claims_count": len(verified_claims),
                    "is_fully_compliant": is_compliant,
                    "stages": [t.stage.value for t in timings],
                },
                "timestamp": datetime.now(timezone.utc).isoformat(),
            }
        ).execute()

        return LoanAnalysisPipelineResponse(
            loan_id=loan_id,
            status=PipelineStage.COMPLETED,
            total_duration_ms=total_duration,
            timings=timings,
            apr_result=apr_response,
            serviceability_result=serviceability_response,
            consistency_result=consistency_response,
            verified_claims=verified_claims,
            vernacular_translations=vernacular_results,
            summary=" ".join(summary_parts),
            is_fully_compliant=is_compliant,
            warnings=warnings,
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Pipeline execution failed at stage {current_stage}: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Pipeline error at stage {current_stage}: {str(e)}",
        )
